

## connection
host = 192.168.1.11
port = 6379
timeout = 2000
##password = 
database = 1

## properties
maxActive = 50
maxIdle = 10
maxWait = 100
minEvictableIdleTimeMillis = 1000
minIdle = 5
numTestsPerEvictionRun = 10
lifo = false
softMinEvictableIdleTimeMillis = 10
testOnBorrow = true
testOnReturn = false
testWhileIdle = false
timeBetweenEvictionRunsMillis = 10
whenExhaustedAction = 1